hides all warnings

In [1]:
import warnings
warnings.filterwarnings('ignore')
# pandas 
import pandas as pd
# numpy
import numpy as np
# stats
# https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ttest_rel.html
from scipy.stats import ttest_rel

############################################################<br>
Read Data <br>
############################################################

assign spreadsheet filename: file

In [2]:
file = 'ttest-data.xlsx'

load spreadsheet xls

In [3]:
xls = pd.ExcelFile(file)

print sheet names

In [4]:
print(xls.sheet_names)

['tTest-1SMwoSD-1', 'tTest-1SMwoSD-2', 'tTest-Ind2SM-1', 'tTest-Ind2SM-2', 'tTest-Dep2SM-1', 'tTest-Dep2SM-2', 'Chi-Sq-GoF-1', 'Chi-Sq-GoF-2', 'Chi-Sq-ToI-1', 'Chi-Sq-ToI-2', 'Anova-1Factor-1', 'Anova-1Factor-2', 'Anova-1Factor-P1']


load a sheet into a dataFrame by name

In [5]:
df = xls.parse('tTest-Dep2SM-2')

print df

In [6]:
colNames = df.columns.tolist()
for colName in colNames:
    print(df[colName].values.flatten())

['A' 'B' 'C' 'D' 'E' 'F' 'G' 'H' 'I' 'J']
[ 790 1010 1220  880 1040  900 1170  820  990  650]
[ 791 1009 1222  878 1041  901 1168  822  991  651]


############################################################<br>
Hypothesis Test<br>
############################################################

Problem	Prices of given products in two given cities is same				

 0.05<br>
-mu - m-nm = 0<br>
-mu - m-nm != 0<br>
woTailed<br>
est: Dep Two Sample Mean

null hyp

In [7]:
Ho = "m-mu - m-nm = 0"
# alt hyp
Ha = "m-mu - m-nm != 0"
# alpha
al = 0.05
# mu - mean
#mu = 66
# tail type
tt = 2
# data
d_mu = df['Mumbai'].values
d_nm = df['NMumbai'].values
d_mu = d_mu[~np.isnan(d_mu)]
d_nm = d_nm[~np.isnan(d_nm)]
# print
print("Ho:", Ho)
print("Ha:", Ha)
print("al:", al)
#print("mu:", mu)
print()
print(d_mu)
print(d_nm)
print("")

Ho: m-mu - m-nm = 0
Ha: m-mu - m-nm != 0
al: 0.05

[ 790 1010 1220  880 1040  900 1170  820  990  650]
[ 791 1009 1222  878 1041  901 1168  822  991  651]



In [8]:
ts, pv = ttest_rel(d_mu, d_nm)
print("t-stat",ts)
print("p-vals",pv)
t2pv = pv
print("2t pv",t2pv)

t-stat -0.840168050416806
p-vals 0.42257162813419624
2t pv 0.42257162813419624


In [13]:
if t2pv<=al:
    print("reject the null hypothesis",Ha)
else:
    print("don't reject the null hypothesis",Ho)

don't reject the null hypothesis m-mu - m-nm = 0
