# Two dependent samples

In [14]:
import warnings
warnings.filterwarnings('ignore')
# pandas 
import pandas as pd
# numpy
import numpy as np
# stats
# https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ttest_rel.html
from scipy.stats import ttest_rel

############################################################<br>
Read Data <br>
############################################################

assign spreadsheet filename: file

In [15]:
file = 'ttest-data.xlsx'

load spreadsheet xls

In [16]:
xls = pd.ExcelFile(file)

print sheet names

In [17]:
print(xls.sheet_names)

['tTest-1SMwoSD-1', 'tTest-1SMwoSD-2', 'tTest-Ind2SM-1', 'tTest-Ind2SM-2', 'tTest-Dep2SM-1', 'tTest-Dep2SM-2', 'Chi-Sq-GoF-1', 'Chi-Sq-GoF-2', 'Chi-Sq-ToI-1', 'Chi-Sq-ToI-2', 'Anova-1Factor-1', 'Anova-1Factor-2', 'Anova-1Factor-P1']


load a sheet into a dataFrame by name

In [18]:
df = xls.parse('tTest-Dep2SM-1')

print df

In [19]:
colNames = df.columns.tolist()
for colName in colNames:
    print(df[colName].values.flatten())

['A' 'B' 'C' 'D' 'E' 'F' 'G' 'H' 'I' 'J']
[ 710  900 1100  890  990  910 1030  800  900  600]
[ 790 1010 1220  880 1040  900 1170  820  990  650]


############################################################<br>
Hypothesis Test<br>
############################################################

Problem	Prices of given products in two given cities is same				

 0.05<br>
-mu - m-pu = 0<br>
-mu - m-pu != 0<br>
woTailed<br>
est: Dep Two Sample Mean

null hyp

In [20]:
Ho = "m-mu - m-pu = 0"
# alt hyp
Ha = "m-mu - m-pu != 0"
# alpha
al = 0.05
# tail type
tt = 2
# data
d_mu = df['Mumbai'].values
d_pu = df['Pune'].values
d_mu = d_mu[~np.isnan(d_mu)]
d_pu = d_pu[~np.isnan(d_pu)]

print

In [21]:
print("Ho:", Ho)
print("Ha:", Ha)
print("al:", al)
#print("mu:", mu)
print()
print(d_mu)
print(d_pu)
print("")

Ho: m-mu - m-pu = 0
Ha: m-mu - m-pu != 0
al: 0.05

[ 790 1010 1220  880 1040  900 1170  820  990  650]
[ 710  900 1100  890  990  910 1030  800  900  600]



In [22]:
ts, pv = ttest_rel(d_mu, d_pu)
print("t-stat",ts)
print("p-vals",pv)
t2pv = pv
print("2t pv",t2pv)

t-stat 3.821699657558558
p-vals 0.004079274360829899
2t pv 0.004079274360829899


In [26]:
if t2pv <= al:
    print("Null Hypothesis: Rejected")
    print("Conclusion:",Ha)
else:
    print("Null Hypothesis: Not Rejected")
    print("Conclusion:",Ho)

Null Hypothesis: Rejected
Conclusion: m-mu - m-nm != 0
